layout_spectrum: 0.6616012
typography_spectrum: 0.7796674
color:
  saturation: 0.9200105
  lightness: 0.4532922
  brandStrength: 0.2876224
  rhythmicContrast: 0.92819
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Yukonjak Alaskan malamutes
