collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9200105
  brandStrength: 0.5338346
  rhythmicContrast: 0.7863408
  brandColors:
    - '#1B2E10'
    - '#0B1608'
    - '#403F3A'
    - '#7B8083'
    - '#64686C'
  lightness: 0.6146616
typography_spectrum: 0.5200501
layout_spectrum: 0.7596965
name: Yukonjak Alaskan malamutes
